--CREATE TABLES
CREATE TABLE USERS (
  ID NUMBER PRIMARY KEY,
  EMAIL VARCHAR(100) NOT NULL,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  AVATAR VARCHAR(100) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  UPDATED_AT TIMESTAMP DEFAULT (CURRENT_TIMESTAMP))